import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
import {transformSync} from 'esbuild';
function app(){const c:any={console,Date,Map,Set,Number,JSON,Math,Intl,document:{addEventListener(){}},mkId:()=>String(Math.random()),saveProducts:async()=>{},savePedidos:async()=>{},savePedidosFinalizados:async()=>{},saveIncomes:async()=>{},saveExpenses:async()=>{},posTotalPagado:(p:any)=>Number(p.anticipo)||0,registrarMovimiento(){},posRunOperation:async(fn:any)=>fn()};c.window=c;c.products=[{id:'p',name:'Playera',stock:5,variants:[{type:'Talla/Color',value:'M / Negro',qty:2},{type:'Talla/Color',value:'L / Negro',qty:3}]}];c.pedidos=[{id:'o',folio:'PE-1',cliente:'Ana',status:'confirmado',total:100,productosInventario:[{id:'p',name:'Playera',variante:'Talla/Color:M / Negro',quantity:2,price:50}]}];c.pedidosFinalizados=[];c.incomes=[];c.expenses=[];runInNewContext(transformSync(readFileSync('src/operations.ts','utf8'),{loader:'ts'}).code,c);runInNewContext(transformSync(readFileSync('src/commerce.ts','utf8'),{loader:'ts'}).code,c);return c;}
it('aparta talla elegida, conserva dinero y libera sin tocar otra talla ni materias primas',async()=>{const c=app();await c.posApartarPedido('o');expect(c.products[0].variants.map((v:any)=>v.qty)).toEqual([0,3]);expect(c.pedidos[0].inventarioDescontado).toBe(true);expect(c.pedidos[0].total).toBe(100);await c.posLiberarApartado('o');expect(c.products[0].variants.map((v:any)=>v.qty)).toEqual([2,3]);expect(c.incomes).toEqual([]);expect(c.expenses).toEqual([]);});

it('rechaza apartar existencias insuficientes y suma lineas repetidas de la misma variante',async()=>{const c=app();c.pedidos[0].productosInventario.push({...c.pedidos[0].productosInventario[0],quantity:1});await expect(c.posApartarPedido('o')).rejects.toThrow('Solo hay 2');expect(c.products[0].stock).toBe(5);});
it('la promocion reparte centavos exactos entre componentes y conserva su variante',()=>{const c=app();const lines=c.posPromocionLineas({nombre:'Combo',precio:99.99,items:[{id:'p',variante:'Talla/Color:M / Negro',quantity:2},{id:'p',variante:'Talla/Color:L / Negro',quantity:1}]},c.products);expect(lines.reduce((s:number,i:any)=>s+Math.round(i.price*100)*i.quantity,0)).toBe(9999);expect(lines.reduce((s:number,i:any)=>s+i.quantity,0)).toBe(3);expect(lines.every((i:any)=>i.posPromocion.nombre==='Combo')).toBe(true);});

it('devolucion recupera piezas elegidas y registra egreso una sola vez sin reescribir la venta',async()=>{const c=app();const p=c.pedidos.pop();Object.assign(p,{status:'finalizado',inventarioDescontado:true,anticipo:100});c.pedidosFinalizados.push(p);await c.posRegistrarDevolucion('o',{index:0,quantity:1,recuperar:true,monto:50,motivo:'Cambio de diseño',method:'cash'});expect(c.products[0].variants[0].qty).toBe(3);expect(c.expenses[0].amount).toBe(50);expect(p.total).toBe(100);await expect(c.posRegistrarDevolucion('o',{index:0,quantity:2,recuperar:true,monto:100,motivo:'Otra',method:'cash'})).rejects.toThrow('cantidad');expect(c.expenses).toHaveLength(1);});

it('capacidad cuenta piezas activas por dia y excluye apartados terminados sin bloquear',()=>{const c=app();c.pedidos[0].entrega='2026-10-01';c.pedidos.push({id:'r',status:'confirmado',entrega:'2026-10-01',productosInventario:[{id:'p',quantity:4}],posDetalle:{apartado:{activo:true}}});const days=c.posCapacidadDias(c.pedidos,'2026-10-01',2,1);expect(days[0]).toMatchObject({piezas:2,pedidos:1,limite:1,exceso:1});expect(days[1].piezas).toBe(0);});

it('tiempo suma sesiones y muestra ganancia por hora solo con costos completos',async()=>{const c=app();await c.posRegistrarTiempo('o',{minutos:30,actividad:'Estampado',fecha:'2026-10-01'});await c.posRegistrarTiempo('o',{minutos:30,actividad:'Empaque',fecha:'2026-10-01'});expect(c.posTiempoResumen(c.pedidos[0])).toMatchObject({minutos:60,gananciaHora:null});c.pedidos[0].posDetalle.costos={reales:{materiales:20,empaque:0,comisiones:0,envio:0,merma:0}};expect(c.posTiempoResumen(c.pedidos[0]).gananciaHora).toBe(80);});

it('cambio por otra talla devuelve la original, descuenta la nueva y cobra la diferencia exacta',async()=>{const c=app();const p=c.pedidos.pop();Object.assign(p,{status:'finalizado',inventarioDescontado:true,anticipo:100});c.pedidosFinalizados.push(p);await c.posRegistrarDevolucion('o',{index:0,quantity:1,recuperar:true,motivo:'Talla',method:'cash',cambio:{id:'p',variante:'Talla/Color:L / Negro',quantity:1,price:70}});expect(c.products[0].variants.map((v:any)=>v.qty)).toEqual([3,2]);expect(c.incomes[0].amount).toBe(20);expect(c.expenses).toHaveLength(0);expect(c.posComDevolvible(p,1)).toBe(1);});
it('rechaza reembolso superior al cobro y no recupera una pieza dañada',async()=>{const c=app();const p=c.pedidos.pop();Object.assign(p,{status:'finalizado',inventarioDescontado:true,anticipo:20});c.pedidosFinalizados.push(p);await expect(c.posRegistrarDevolucion('o',{index:0,quantity:1,recuperar:true,monto:50,motivo:'Daño',method:'cash'})).rejects.toThrow('reembolso');expect(c.products[0].stock).toBe(5);await c.posRegistrarDevolucion('o',{index:0,quantity:1,recuperar:false,monto:20,motivo:'Daño',method:'cash'});expect(c.products[0].stock).toBe(5);expect(c.expenses[0].amount).toBe(20);});
it('el extra conserva precio y unidades como servicio sin cambiar existencias',()=>{const c=app();const line=c.posPersonalizacionLinea('Nombre individual',15.5,2);expect(line).toMatchObject({id:'libre',quantity:2,price:15.5,posPersonalizacion:true});expect(c.products[0].stock).toBe(5);expect(()=>c.posPersonalizacionLinea('Nombre',-1,2)).toThrow('Importe');});

it('apartar reduce disponibilidad pero conserva piezas fisicas para valorar inventario',async()=>{const c=app();await c.posApartarPedido('o');expect(c.posComApartadas('p')).toBe(2);expect(c.posComStockFisico(c.products[0])).toBe(5);});
