// ponytail: la ficha JSON y la transaccion existentes conservan el registro comercial.
function posComPedido(id:string){const p=[...(window.pedidos||[]),...(window.pedidosFinalizados||[])].find(x=>String(x.id)===String(id));if(!p)throw Error('Pedido no encontrado.');return p;}
function posComCantidad(n:any){const q=Number(n);if(!Number.isSafeInteger(q)||q<1)throw Error('La cantidad debe ser un entero mayor a cero.');return q;}
function posComCentavos(n:any){const x=Number(n);if(!Number.isFinite(x)||x<0||x>100000000)throw Error('Importe inválido.');return Math.round(x*100);}
function posComVariante(p:any,key:string){if(!(p.variants||[]).length)return null;const v=p.variants.find((v:any)=>`${v.type||v.tipo||''}:${v.value||v.valor||''}`===String(key));if(!v)throw Error(`Elige una variante válida de ${p.name}.`);return v;}
function posComStock(items:any[],direction:number,reason:string){
 const plans=new Map<string,any>();
 for(const i of items){if(i.id==='libre')continue;const p=(window.products||[]).find(p=>String(p.id)===String(i.id));if(!p||['servicio','materia_prima','pack'].includes(p.tipo))throw Error('Selecciona piezas terminadas existentes.');const v=posComVariante(p,i.variante),key=JSON.stringify([p.id,i.variante||'']),q=posComCantidad(i.quantity||i.cantidad);const prior=plans.get(key);if(prior)prior.qty+=q;else plans.set(key,{p,v,qty:q});}
 if(!plans.size)throw Error('El pedido no contiene piezas terminadas.');
 for(const {p,v,qty} of plans.values()){const available=Number(v?v.qty:p.stock)||0;if(direction<0&&available<qty)throw Error(`Solo hay ${available} piezas terminadas de ${p.name}${v?' · '+(v.value||v.valor):''}.`);}
 for(const {p,v,qty} of plans.values()){const before=Number(v?v.qty:p.stock)||0,after=before+direction*qty;if(v){v.qty=after;p.stock=p.variants.reduce((s:number,v:any)=>s+(Number(v.qty)||0),0);}else p.stock=after;registrarMovimiento({productoId:p.id,productoNombre:p.name,tipo:direction>0?'entrada':'salida',cantidad:direction*qty,motivo:reason+(v?' · '+(v.value||v.valor):''),stockAntes:before,stockDespues:after});}
 return plans.size;
}
async function posComGuardarPedido(p:any){if((window.pedidos||[]).includes(p))await savePedidos();else await savePedidosFinalizados();}
async function posApartarPedido(id:string){
 return posRunOperation(async()=>{const p=posComPedido(id);if(!(window.pedidos||[]).includes(p)||['cancelado','finalizado','entregado'].includes(p.status))throw Error('Aparta desde un pedido activo.');if(p.inventarioDescontado)throw Error('Este pedido ya tiene el inventario descontado.');
 const items=JSON.parse(JSON.stringify((p.productosInventario||[]).filter((i:any)=>i.id!=='libre')));posComStock(items,-1,`Apartado ${p.folio}`);p.posDetalle={...p.posDetalle,apartado:{activo:true,modo:'terminado',fecha:new Date().toISOString(),items}};p.inventarioDescontado=true;await saveProducts();await posComGuardarPedido(p);},'Apartar piezas terminadas');
}
function posComRestaurarApartado(p:any){const a=p.posDetalle?.apartado;if(!a?.activo)return false;posComStock(a.items,1,`Liberación de apartado ${p.folio}`);a.activo=false;a.liberado=new Date().toISOString();return true;}
async function posLiberarApartado(id:string){return posRunOperation(async()=>{const p=posComPedido(id);if(!(window.pedidos||[]).includes(p)||!p.posDetalle?.apartado?.activo)throw Error('No hay un apartado activo.');posComRestaurarApartado(p);p.posDetalle.apartado.modo='liberado';p.inventarioDescontado=false;await saveProducts();await posComGuardarPedido(p);},'Liberar apartado');}
function posComApartadas(productId:string){return (window.pedidos||[]).filter(p=>!['cancelado','finalizado','entregado'].includes(p.status)&&p.posDetalle?.apartado?.activo).reduce((s:number,p:any)=>s+p.posDetalle.apartado.items.filter((i:any)=>String(i.id)===String(productId)).reduce((n:number,i:any)=>n+Number(i.quantity||i.cantidad||0),0),0);}
Object.assign(window,{posApartarPedido,posLiberarApartado,posComStock,posComRestaurarApartado,posComApartadas});

function posPromocionLineas(promo:any,products:any[]){
 const target=posComCentavos(promo.precio);if(!target||!String(promo.nombre||'').trim())throw Error('Escribe nombre y precio de la promoción.');
 const entries=(promo.items||[]).map((i:any)=>{const p=products.find(p=>String(p.id)===String(i.id));if(!p||['materia_prima','pack','servicio'].includes(p.tipo))throw Error('El componente de la promoción no está disponible.');posComVariante(p,i.variante);const qty=posComCantidad(i.quantity);const value=typeof window.pvGetPrecio==='function'&&p.tipo==='producto_variable'?window.pvGetPrecio(p,qty,i.variante):Number(p.price)||0;return {i,p,qty,weight:Math.max(1,posComCentavos(value))*qty};});
 if(entries.reduce((s:number,e:any)=>s+e.qty,0)<2)throw Error('Incluye al menos dos piezas en la promoción.');
 const weight=entries.reduce((s:number,e:any)=>s+e.weight,0),id=mkId(),out:any[]=[];let rest=target;
 entries.forEach((e:any,index:number)=>{const amount=index===entries.length-1?rest:Math.floor(target*e.weight/weight);rest-=amount;const unit=Math.floor(amount/e.qty),extra=amount%e.qty;const base={id:e.p.id,name:e.p.name,variante:e.i.variante||null,posPromocion:{id,nombre:String(promo.nombre).trim(),total:target/100}};if(e.qty>extra)out.push({...base,quantity:e.qty-extra,price:unit/100});if(extra)out.push({...base,quantity:extra,price:(unit+1)/100});});
 return out;
}
Object.assign(window,{posPromocionLineas});

function posComLineasVendidas(p:any){return [...(p.productosInventario||[]),...(p.posDetalle?.itemsCambio||[])];}
function posComDevolvible(p:any,index:number){const line=posComLineasVendidas(p)[index];if(!line)return 0;return Number(line.quantity||line.cantidad||1)-(p.posDetalle?.devoluciones||[]).filter((r:any)=>r.index===index).reduce((s:number,r:any)=>s+Number(r.quantity||0),0);}
function posComCobradoNeto(p:any){return Math.max(0,posTotalPagado(p)+(p.posDetalle?.devoluciones||[]).reduce((s:number,r:any)=>s+(Number(r.cobro)||0)-(Number(r.reembolso)||0),0));}
async function posRegistrarDevolucion(id:string,input:any){
 return posRunOperation(async()=>{
 const p=posComPedido(id);if(!(window.pedidosFinalizados||[]).includes(p)||!['finalizado','entregado','completado'].includes(p.status))throw Error('Selecciona un pedido vendido del historial.');
 if(input.before&&input.before!==JSON.stringify(p))throw Error('El pedido cambió. Vuelve a abrirlo.');
 const index=Number(input.index),quantity=posComCantidad(input.quantity);if(!Number.isSafeInteger(index)||quantity>posComDevolvible(p,index))throw Error('La cantidad supera las piezas pendientes de devolver.');
 const item=posComLineasVendidas(p)[index],reason=String(input.motivo||'').trim();if(!reason)throw Error('Escribe el motivo del cambio o devolución.');if(!['cash','transferencia','card'].includes(input.method))throw Error('Elige el método de devolución o cobro.');
 const original=posComCentavos(item.price)*quantity;
 let refund=posComCentavos(input.monto||0),charge=0,replacement:any=null;
 if(input.cambio){const prod=(window.products||[]).find(p=>String(p.id)===String(input.cambio.id));if(!prod)throw Error('Producto de cambio no encontrado.');posComVariante(prod,input.cambio.variante);const q=posComCantidad(input.cambio.quantity),price=posComCentavos(input.cambio.price);replacement={id:prod.id,name:prod.name,variante:input.cambio.variante||null,quantity:q,price:price/100};const delta=price*q-original;refund=Math.max(0,-delta);charge=Math.max(0,delta);}
 if(refund>Math.min(original,posComCentavos(posComCobradoNeto(p))))throw Error('El reembolso supera el valor devuelto o el dinero cobrado disponible.');
 // Validar la salida antes de devolver piezas: la transaccion tambien revierte fallos posteriores.
 if(replacement){const prod=window.products.find(p=>String(p.id)===String(replacement.id)),v=posComVariante(prod,replacement.variante);const recovery=input.recuperar&&String(item.id)===String(replacement.id)&&String(item.variante||'')===String(replacement.variante||'')?quantity:0;if((Number(v?v.qty:prod.stock)||0)+recovery<replacement.quantity)throw Error('No hay piezas terminadas suficientes para el cambio.');}
 if(input.recuperar&&item.id!=='libre')posComStock([{...item,quantity}],1,`Devolución ${p.folio}: ${reason}`);
 if(replacement)posComStock([replacement],-1,`Cambio ${p.folio}: ${reason}`);
 const entry={id:mkId(),fecha:new Date().toISOString(),index,quantity,recuperar:!!input.recuperar,motivo:reason,reembolso:refund/100,cobro:charge/100,method:input.method,cambio:replacement};
 p.posDetalle={...p.posDetalle,devoluciones:[...(p.posDetalle?.devoluciones||[]),entry],itemsCambio:[...(p.posDetalle?.itemsCambio||[]),...(replacement?[replacement]:[])]};
 const cash={id:entry.id,date:posComHoy(),concept:`${refund?'Devolución':'Diferencia de cambio'} ${p.folio} · ${reason}`,amount:(refund||charge)/100,method:input.method,category:'Cambios y devoluciones',etiqueta:'Cambios y devoluciones',client:p.cliente};
 if(refund){window.expenses.push(cash);await saveExpenses();}if(charge){window.incomes.push(cash);await saveIncomes();}
 await saveProducts();await posComGuardarPedido(p);return entry;
 },'Registrar cambio o devolución');
}
function posComPuedeReescribir(p:any){if(p?.posDetalle?.devoluciones?.length){manekiToastExport('Este pedido tiene cambios o devoluciones registrados. Consúltalos desde su ficha comercial; conserva la venta original.','warn');return false;}return true;}
Object.assign(window,{posRegistrarDevolucion,posComLineasVendidas,posComDevolvible,posComCobradoNeto,posComPuedeReescribir});

function posComHoy(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function posComFecha(s:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw Error('Fecha inválida.');const d=new Date(s+'T12:00:00Z');if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==s)throw Error('Fecha inválida.');return d;}
function posCapacidadDias(orders:any[],start:string,days=30,limite=0){
 const date=posComFecha(start);if(!Number.isSafeInteger(days)||days<1||days>90)throw Error('Elige de 1 a 90 días.');if(!Number.isSafeInteger(limite)||limite<0)throw Error('Capacidad inválida.');
 return Array.from({length:days},(_,index)=>{const d=new Date(date.getTime()+index*86400000),fecha=d.toISOString().slice(0,10);const list=orders.filter(p=>p.entrega===fecha&&['confirmado','pago','produccion'].includes(p.status)&&!p.posDetalle?.apartado?.activo);const piezas=list.reduce((sum,p)=>sum+(p.productosInventario||[]).filter((i:any)=>i.id!=='libre').reduce((s:number,i:any)=>s+(Number(i.quantity||i.cantidad)||0),0),0);return {fecha,piezas,pedidos:list.length,limite,exceso:limite?Math.max(0,piezas-limite):0,folios:list.map(p=>p.folio||p.cliente).join(', ')};});
}
Object.assign(window,{posCapacidadDias});

async function posRegistrarTiempo(id:string,input:any){return posRunOperation(async()=>{const p=posComPedido(id),minutos=Number(input.minutos),actividad=String(input.actividad||'').trim();if(!Number.isSafeInteger(minutos)||minutos<1||minutos>1440)throw Error('Registra de 1 a 1440 minutos por sesión.');if(!actividad)throw Error('Escribe la actividad realizada.');posComFecha(input.fecha);if(input.before&&input.before!==JSON.stringify(p))throw Error('El pedido cambió. Vuelve a abrirlo.');p.posDetalle={...p.posDetalle,tiempos:[...(p.posDetalle?.tiempos||[]),{id:mkId(),fecha:input.fecha,minutos,actividad}]};await posComGuardarPedido(p);},'Registrar tiempo de producción');}
function posTiempoResumen(p:any){const minutos=(p.posDetalle?.tiempos||[]).reduce((s:number,t:any)=>s+(Number(t.minutos)||0),0),ajuste=(p.posDetalle?.devoluciones||[]).reduce((s:number,r:any)=>s+Number(r.cobro||0)-Number(r.reembolso||0),0);const profit=window.posRentabilidad?.({...p,total:Number(p.total||0)+ajuste},p.posDetalle?.costos||{});return {minutos,gananciaHora:minutos&&profit?.ganancia!=null?Math.round(profit.ganancia*60/minutos*100)/100:null};}
function posPersonalizacionLinea(nombre:string,precio:any,cantidad:any){const name=String(nombre||'').trim();if(!name)throw Error('Describe la personalización.');const cents=posComCentavos(precio),qty=posComCantidad(cantidad);if(!cents)throw Error('Escribe el precio del extra.');return {id:'libre',name:`Personalización · ${name}`,quantity:qty,price:cents/100,variante:null,posPersonalizacion:true};}
Object.assign(window,{posRegistrarTiempo,posTiempoResumen,posPersonalizacionLinea});

function posComActualizar(){for(const key of ['renderPedidosTable','renderHistorialPedidos','renderInventoryTable','renderBalance','updateDashboard']){try{window[key]?.();}catch(e){console.warn('Registro guardado; vista pendiente de refrescar:',key);}}}
function posComForm(dialog:HTMLDialogElement,html:string,save:(data:FormData)=>Promise<any>,message='Registro guardado.'){
 const form=document.createElement('form');form.className='pos-commerce-form';form.innerHTML=html;
 const status=document.createElement('p');status.setAttribute('role','status');const button=document.createElement('button');button.type='submit';button.className='mk-btn-primary';button.textContent='Guardar';form.append(status,button);dialog.appendChild(form);
 form.onsubmit=async e=>{e.preventDefault();button.disabled=true;try{await save(new FormData(form));posComActualizar();dialog.close();const parent=document.querySelector('dialog.pos-commerce-dialog[open] select[aria-label="Pedido comercial"]') as HTMLSelectElement;if(parent){const id=parent.value;(parent.closest('dialog') as HTMLDialogElement).close();posAbrirComercial(id);}manekiToastExport(message,'ok');}catch(e:any){status.textContent=e.message||'No se pudo guardar.';button.disabled=!!e.pendingSync;}};
 return form;
}
function posComProductosOptions(){return (window.products||[]).filter(p=>!['materia_prima','servicio','pack'].includes(p.tipo)&&p.activo!==false).flatMap(p=>(p.variants?.length?p.variants:[null]).map(v=>`<option value="${_esc(JSON.stringify([String(p.id),v?`${v.type||v.tipo}:${v.value||v.valor}`:null]))}">${_esc(p.name)}${v?' · '+_esc(v.value||v.valor):''}</option>`)).join('');}
function posAbrirComercial(id?:string){
 const orders=[...(window.pedidos||[]),...(window.pedidosFinalizados||[])];const p=id?posComPedido(id):orders[0];const d=posDialog('Apartados, cambios y tiempo');d.classList.add('pos-commerce-dialog');if(!p){d.append('Crea un pedido para usar estas herramientas.');return;}
 const select=document.createElement('select');select.setAttribute('aria-label','Pedido comercial');select.innerHTML=orders.map(x=>`<option value="${_esc(String(x.id))}">${_esc(x.folio)} · ${_esc(x.cliente)}${(window.pedidosFinalizados||[]).includes(x)?' · Historial':''}</option>`).join('');select.value=String(p.id);select.onchange=()=>{d.close();posAbrirComercial(select.value);};d.appendChild(select);
 const identity=document.createElement('p');identity.textContent=`${p.cliente} · ${p.folio} · Total ${fmtMoney(p.total)} · Cobrado neto ${fmtMoney(posComCobradoNeto(p))}`;d.appendChild(identity);
 const state=document.createElement('p');const a=p.posDetalle?.apartado;state.textContent=a?.activo&&!(window.pedidosFinalizados||[]).includes(p)?'Piezas apartadas · fuera de disponibilidad':p.inventarioDescontado?'Inventario ya descontado':'Sin apartado';d.appendChild(state);
 if((window.pedidos||[]).includes(p)&&!['cancelado','finalizado','entregado'].includes(p.status)){const b=document.createElement('button');b.className='mk-btn-secondary';b.textContent=a?.activo?'Liberar apartado':'Apartar piezas terminadas';b.disabled=!!p.inventarioDescontado&&!a?.activo;b.onclick=async()=>{b.disabled=true;try{if(a?.activo)await posLiberarApartado(String(p.id));else await posApartarPedido(String(p.id));posComActualizar();d.close();posAbrirComercial(String(p.id));}catch(e:any){state.textContent=e.message;b.disabled=!!e.pendingSync;}};d.appendChild(b);}
 const tools=document.createElement('div');tools.className='pos-commerce-tools';const time=document.createElement('button');time.className='mk-btn-secondary';time.textContent='Registrar tiempo';time.onclick=()=>posAbrirTiempo(String(p.id));tools.appendChild(time);
 if((window.pedidosFinalizados||[]).includes(p)&&['finalizado','entregado','completado'].includes(p.status)){const r=document.createElement('button');r.className='mk-btn-secondary';r.textContent='Cambio / devolución';r.onclick=()=>posAbrirDevolucion(String(p.id));tools.appendChild(r);}d.appendChild(tools);
 const summary=posTiempoResumen(p),text=document.createElement('p');text.textContent=`Tiempo registrado: ${summary.minutos} min · Ganancia por hora: ${summary.gananciaHora==null?'pendiente de costo completo':fmtMoney(summary.gananciaHora)}`;d.appendChild(text);
 const log=document.createElement('ul');for(const r of p.posDetalle?.devoluciones||[]){const li=document.createElement('li');li.textContent=`${r.fecha.slice(0,10)} · ${r.quantity} piezas · ${r.motivo} · Reembolsado ${fmtMoney(r.reembolso)} · Cobrado ${fmtMoney(r.cobro)} · ${r.recuperar?'Recuperadas':'Sin recuperar'}`;log.appendChild(li);}for(const t of p.posDetalle?.tiempos||[]){const li=document.createElement('li');li.textContent=`${t.fecha} · ${t.actividad}: ${t.minutos} min`;log.appendChild(li);}d.appendChild(log);
}
function posAbrirTiempo(id:string){const p=posComPedido(id),before=JSON.stringify(p),d=posDialog(`Tiempo · ${p.folio}`);posComForm(d,`<label>Fecha<input type="date" name="fecha" value="${posComHoy()}" required></label><label>Actividad<input name="actividad" placeholder="Estampado, diseño, empaque…" required maxlength="120"></label><label>Minutos efectivos<input type="number" name="minutos" min="1" max="1440" step="1" required></label><p>Registra solo tiempo trabajado. Puedes añadir varias sesiones.</p>`,async data=>posRegistrarTiempo(id,{fecha:data.get('fecha'),actividad:data.get('actividad'),minutos:data.get('minutos'),before}));}
function posAbrirDevolucion(id:string){
 const p=posComPedido(id),before=JSON.stringify(p),d=posDialog(`Cambio / devolución · ${p.folio}`);d.classList.add('pos-commerce-dialog');
 const options=posComLineasVendidas(p).map((i:any,index:number)=>({i,index,left:posComDevolvible(p,index)})).filter(x=>x.left>0).map(({i,index,left})=>`<option value="${index}">${_esc(i.name)}${i.variante?' · '+_esc(i.variante):''} · ${left} disponibles para devolver</option>`).join('');if(!options){d.append('Todas las piezas ya tienen una devolución registrada.');return;}
 const form=posComForm(d,`<label>Tipo<select name="tipo"><option value="devolucion">Devolución</option><option value="cambio">Cambio por otra pieza</option></select></label><label>Pieza original<select name="index">${options}</select></label><label>Cantidad<input name="quantity" type="number" min="1" step="1" value="1" required></label><label class="pos-commerce-check"><input name="recuperar" type="checkbox"> La pieza está en buen estado y vuelve al inventario</label><div data-refund><label>Dinero a devolver<input name="monto" type="number" min="0" step="0.01" value="0"></label></div><fieldset data-replacement hidden><legend>Nueva pieza</legend><label>Producto y variante<select name="replacement">${posComProductosOptions()}</select></label><label>Cantidad nueva<input name="newQty" type="number" min="1" step="1" value="1"></label><label>Precio por pieza nueva<input name="newPrice" type="number" min="0" step="0.01"></label></fieldset><label>Método<select name="method"><option value="cash">Efectivo</option><option value="transferencia">Transferencia</option><option value="card">Tarjeta</option></select></label><label>Motivo<input name="motivo" required maxlength="200"></label><p data-estimate></p>`,async data=>{const input:any={index:data.get('index'),quantity:data.get('quantity'),recuperar:data.has('recuperar'),monto:data.get('monto'),motivo:data.get('motivo'),method:data.get('method'),before};if(data.get('tipo')==='cambio'){const [product,variante]=JSON.parse(String(data.get('replacement')));input.cambio={id:product,variante,quantity:data.get('newQty'),price:data.get('newPrice')};}return posRegistrarDevolucion(id,input);});
 const control=(name:string)=>form.elements.namedItem(name) as HTMLInputElement;
 const update=(price=false)=>{const swap=control('tipo').value==='cambio';(form.querySelector('[data-replacement]') as HTMLElement).hidden=!swap;(form.querySelector('[data-refund]') as HTMLElement).hidden=swap;const item=posComLineasVendidas(p)[Number(control('index').value)],qty=Number(control('quantity').value)||1;control('quantity').max=String(posComDevolvible(p,Number(control('index').value)));if(swap&&price){const [id,key]=JSON.parse(control('replacement').value),product=window.products.find(p=>String(p.id)===id);control('newPrice').value=String(product?.tipo==='producto_variable'?window.pvGetPrecio?.(product,Number(control('newQty').value)||1,key)||0:product?.price||0);}const delta=swap?(Number(control('newQty').value)||0)*(Number(control('newPrice').value)||0)-qty*(Number(item?.price)||0):-(Number(control('monto').value)||0);form.querySelector('[data-estimate]').textContent=swap?`${delta>0?'Cobrar diferencia':delta<0?'Devolver diferencia':'Sin diferencia'} ${fmtMoney(Math.abs(delta))}`:`Reembolso máximo de estas piezas: ${fmtMoney(Math.min(posComCobradoNeto(p),qty*Number(item?.price||0)))}. Si no hubo devolución de dinero, conserva $0.`;};
 form.oninput=()=>update();control('tipo').onchange=()=>update(true);control('replacement').onchange=()=>update(true);control('newQty').onchange=()=>update(true);update(true);
}
Object.assign(window,{posAbrirComercial,posAbrirTiempo,posAbrirDevolucion});

async function posAbrirCapacidad(){
 const d=posDialog('Capacidad de producción');d.classList.add('pos-commerce-dialog');const config=await sbLoad('posCapacidad',{piezas:0});if(!d.isConnected)return;
 const form=document.createElement('form');form.className='pos-commerce-form';form.innerHTML=`<p>Pedidos confirmados, pagados o en producción. Excluye apartados de piezas ya terminadas. Es una referencia; no impide guardar pedidos.</p><label>Desde<input name="desde" type="date" value="${posComHoy()}" required></label><label>Capacidad diaria en piezas<input name="limite" type="number" min="0" step="1" value="${Number(config.piezas)||0}"><small>0 = sin límite definido</small></label><button class="mk-btn-secondary" type="submit">Guardar capacidad</button><p role="status"></p><div class="pos-capacity-scroll"><table><thead><tr><th>Entrega</th><th>Pedidos</th><th>Piezas</th><th>Capacidad</th></tr></thead><tbody></tbody></table></div>`;d.appendChild(form);
 const date=form.elements.namedItem('desde') as HTMLInputElement,limit=form.elements.namedItem('limite') as HTMLInputElement,status=form.querySelector('[role=status]');
 const render=()=>{try{form.querySelector('tbody').innerHTML=posCapacidadDias(window.pedidos||[],date.value,30,Number(limit.value)||0).map(day=>`<tr data-over="${day.exceso>0}"><td><time>${_esc(day.fecha)}</time><small>${_esc(day.folios)}</small></td><td>${day.pedidos}</td><td>${day.piezas}</td><td>${day.limite?day.exceso?'Excede por '+day.exceso:day.piezas+'/'+day.limite:'Sin límite'}</td></tr>`).join('');status.textContent='';}catch(e:any){status.textContent=e.message;}};date.onchange=render;limit.oninput=render;render();
 form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;try{posCapacidadDias([],date.value,1,Number(limit.value));await sbSave('posCapacidad',{piezas:Number(limit.value)});status.textContent='Capacidad guardada.';}catch(e:any){status.textContent=e.message;}finally{b.disabled=false;}};
}
function posAbrirPersonalizacion(){
 const d=posDialog('Precio por personalización');posComForm(d,`<label>Extra<select name="tipo"><option>Impresión en ambas caras</option><option>Nombre individual</option><option>Tamaño de impresión</option><option>Técnica especial</option><option>Otro</option></select></label><label>Detalle opcional<input name="detalle" maxlength="150" placeholder="Ej. Espalda, 20 cm, vinil…"></label><label>Precio por unidad<input name="precio" type="number" min="0.01" step="0.01" required></label><label>Unidades que llevan el extra<input name="cantidad" type="number" min="1" step="1" value="1" required></label><p>Se añade como servicio: aparece en total y documentos, sin descontar inventario.</p>`,async data=>{const line=posPersonalizacionLinea(String(data.get('tipo'))+(data.get('detalle')?' · '+data.get('detalle'):''),data.get('precio'),data.get('cantidad'));window.pedidoProductosSeleccionados=window.pedidoProductosSeleccionados||[];window.pedidoProductosSeleccionados.push(line);window.renderPedidoProductosList?.();const modal=document.getElementById('pedidoModal');if(modal)(modal as any)._mkDirty=true;},'Añadido al pedido. Guarda el pedido para conservarlo.');
}
async function posAbrirPromociones(){
 if(typeof window.ensureInventario==='function')await window.ensureInventario();const d=posDialog('Promociones combinadas');d.classList.add('pos-commerce-dialog');const promos=await sbLoad('posPromociones',[]);if(!d.isConnected)return;
 const info=document.createElement('p');info.textContent='Combina productos y variantes. El precio especial conserva el descuento de cada componente al vender.';d.appendChild(info);
 const status=document.createElement('p');status.setAttribute('role','status');d.appendChild(status);
 for(const promo of promos.filter(p=>p.activa!==false)){
 const row=document.createElement('div');row.className='pos-promo-row';const label=document.createElement('strong');label.textContent=`${promo.nombre} · ${fmtMoney(promo.precio)}`;const count=document.createElement('input');count.type='number';count.min='1';count.step='1';count.value='1';count.setAttribute('aria-label','Paquetes de '+promo.nombre);const use=document.createElement('button');use.type='button';use.className='mk-btn-secondary';use.textContent='Añadir al pedido';use.disabled=!!document.getElementById('pedidoModal')?.classList.contains('hidden');use.onclick=()=>{try{const n=posComCantidad(count.value);const lines=posPromocionLineas({...promo,precio:Number(promo.precio)*n,items:promo.items.map((i:any)=>({...i,quantity:posComCantidad(i.quantity)*n}))},window.products||[]);window.pedidoProductosSeleccionados=window.pedidoProductosSeleccionados||[];window.pedidoProductosSeleccionados.push(...lines);window.renderPedidoProductosList?.();const modal=document.getElementById('pedidoModal');if(modal)(modal as any)._mkDirty=true;d.close();}catch(e:any){status.textContent=e.message;}};row.append(label,count,use);d.appendChild(row);
 }
 const form=posComForm(d,`<details open><summary>Crear una promoción</summary><label>Nombre<input name="nombre" required maxlength="100" placeholder="Playera + taza"></label><label>Precio del paquete<input name="precio" type="number" min="0.01" step="0.01" required></label><div data-components></div><button type="button" class="mk-btn-secondary" data-add>Añadir componente</button></details>`,async data=>{const rows=Array.from(form.querySelectorAll('[data-component]')) as HTMLElement[];const items=rows.map(row=>{const [id,variante]=JSON.parse((row.querySelector('select') as HTMLSelectElement).value);return {id,variante,quantity:posComCantidad((row.querySelector('input') as HTMLInputElement).value)};});const promo={id:mkId(),nombre:String(data.get('nombre')).trim(),precio:Number(data.get('precio')),items,activa:true};posPromocionLineas(promo,window.products||[]);await sbSave('posPromociones',[...promos,promo]);});
 const add=()=>{const row=document.createElement('div');row.dataset.component='';row.className='pos-promo-component';row.innerHTML=`<label>Producto y variante<select required>${posComProductosOptions()}</select></label><label>Piezas<input type="number" min="1" step="1" value="1" required></label>`;const remove=document.createElement('button');remove.type='button';remove.className='mk-btn-secondary';remove.textContent='Quitar';remove.onclick=()=>row.remove();row.appendChild(remove);form.querySelector('[data-components]').appendChild(row);};form.querySelector('[data-add]').addEventListener('click',add);add();add();
}
Object.assign(window,{posAbrirCapacidad,posAbrirPersonalizacion,posAbrirPromociones});

async function posComCargarConfig(){const [promos,capacity]=await Promise.all([sbLoad('posPromociones',[]),sbLoad('posCapacidad',{piezas:0})]);window.posPromociones=promos;window.posCapacidad=capacity;}
window.posComCargarConfig=posComCargarConfig;

function posComStockFisico(p:any){return Math.max(0,Number(p.stock)||0)+posComApartadas(String(p.id));}
window.posComStockFisico=posComStockFisico;
